pipeline {
    agent any

    environment {
        SSH_KEY = credentials('ec2-ssh-key')
        DOCKER_IMAGE = 'mohamedashraf001/mymobackend:latest'
        DOCKERHUB_CRED = 'dockerhub-credentials'
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "🔄 Checking out code..."
                git branch: 'main', url: 'https://github.com/mohamedashraf001/node-app-infra-pipeline.git'
            }
        }

     stage('Build Docker Image') {
            steps {
                script {
                    echo "📦 Building Docker image..."
                    sh 'DOCKER_BUILDKIT=0 docker build -t mohamedashraf001/mymobackend:latest .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    echo "🚀 Pushing Docker image to Docker Hub..."
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CRED) {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }

        stage('Deploy on EC2') {
            steps {
                echo "🖥️ Deploying on EC2 via Ansible..."
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ansible-playbook -i ansible/inventory/hosts.ini \
                        ansible/playbooks/deploy-backend.yml -u ubuntu
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline finished successfully!'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
    }
}
