pipeline {
    agent any

    environment {
        SSH_KEY = credentials('ec2-ssh-key')          
        DOCKER_IMAGE = 'mohamedashraf001/mymobackend:latest'  
        DOCKERHUB_CRED = 'dockerhub-credentials'    
        EC2_USER = 'ubuntu'                           
        EC2_HOST = '18.207.102.132'              
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/mohamedashraf001/node-app-infra-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CRED) {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }

     stage('Deploy Docker on EC2') {
    steps {
        sshagent(['ec2-ssh-key']) {   // uses the Jenkins SSH credential
            sh """
            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} "bash -c '
                docker stop myapp || true &&
                docker rm myapp || true &&
                docker pull ${DOCKER_IMAGE} &&
                docker run -d --name myapp -p 5000:3000 --restart unless-stopped ${DOCKER_IMAGE}'
            "
            """
        }
    }
}

    }

    post {
        success { echo '✅ Pipeline finished successfully!' }
        failure { echo '❌ Pipeline failed!' }
    }
}
